apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
      - name: review
        image: m1100/review-service:latest
        ports:
        - containerPort: 5002
